# Generated by Django 4.2.7 on 2025-08-05 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', help_text='Status of this record', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated)', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the category', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image for display', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which categories should be displayed')),
                ('featured', models.BooleanField(default=False, help_text='Whether this category should be featured on homepage')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for creating hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='categories_slug_b4303a_idx'), models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'), models.Index(fields=['featured'], name='categories_feature_2ee071_idx'), models.Index(fields=['parent'], name='categories_parent__7983b2_idx'), models.Index(fields=['sort_order'], name='categories_sort_or_77e69f_idx')],
            },
        ),
    ]
