# apps/categories/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CategoryViewSet

app_name = 'categories'

# Create router and register viewsets
router = DefaultRouter()
router.register(r'', CategoryViewSet, basename='category')

urlpatterns = [
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET    /categories/                    - List all categories
# POST   /categories/                    - Create new category
# GET    /categories/{slug}/             - Retrieve category details
# PUT    /categories/{slug}/             - Update category (full)
# PATCH  /categories/{slug}/             - Update category (partial)
# DELETE /categories/{slug}/             - Delete category
# GET    /categories/tree/               - Get category tree structure
# GET    /categories/featured/           - Get featured categories
# GET    /categories/{slug}/products/    - Get products in category
# POST   /categories/bulk_action/        - Perform bulk actions
# GET    /categories/search/             - Advanced category search
# POST   /categories/{slug}/toggle_featured/ - Toggle featured status
# POST   /categories/{slug}/toggle_active/   - Toggle active status
# GET    /categories/stats/              - Get category statistics