# Generated by Django 4.2.7 on 2025-08-11 21:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('cod', 'Cash on Delivery')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentage_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), max_digits=12)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='payment_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method Configuration',
                'verbose_name_plural': 'Payment Method Configurations',
                'db_table': 'payment_method_configs',
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_details', to='payments.payment')),
            ],
            options={
                'db_table': 'mobile_money_payments',
            },
        ),
        migrations.CreateModel(
            name='CashOnDeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('delivery_phone', models.CharField(max_length=15)),
                ('delivery_notes', models.TextField(blank=True)),
                ('cash_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admin_notified', models.BooleanField(default=False)),
                ('admin_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('collection_notes', models.TextField(blank=True)),
                ('delivery_attempted', models.BooleanField(default=False)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cod_payments', to=settings.AUTH_USER_MODEL)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cod_payments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cod_details', to='payments.payment')),
            ],
            options={
                'db_table': 'cod_payments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['payment', 'transaction_type'], name='payment_tra_payment_de4e56_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['external_reference'], name='payment_tra_externa_28eafd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='payment_web_provide_e7082c_idx'), models.Index(fields=['processed'], name='payment_web_process_d3b66c_idx'), models.Index(fields=['payment'], name='payment_web_payment_17beb2_idx'), models.Index(fields=['created_at'], name='payment_web_created_f9d7cb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='payments_referen_a186d6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_transaction_id'], name='payments_externa_c63e06_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_method'], name='payments_status_0c14d6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['phone_number'], name='mobile_mone_phone_n_5f3e89_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['provider_request_id'], name='mobile_mone_provide_b2800f_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneypayment',
            index=models.Index(fields=['provider_transaction_id'], name='mobile_mone_provide_909ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='cashondeliverypayment',
            index=models.Index(fields=['delivery_phone'], name='cod_payment_deliver_3a6827_idx'),
        ),
        migrations.AddIndex(
            model_name='cashondeliverypayment',
            index=models.Index(fields=['assigned_to'], name='cod_payment_assigne_677694_idx'),
        ),
        migrations.AddIndex(
            model_name='cashondeliverypayment',
            index=models.Index(fields=['collected_by'], name='cod_payment_collect_b3570a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashondeliverypayment',
            index=models.Index(fields=['admin_notified'], name='cod_payment_admin_n_c1144a_idx'),
        ),
    ]
