# Generated by Django 4.2.7 on 2025-08-11 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('cod_order', 'Cash on Delivery Order'), ('payment_received', 'Payment Received'), ('admin_invitation', 'Admin Invitation'), ('flash_sale_started', 'Flash Sale Started'), ('flash_sale_ending', 'Flash Sale Ending Soon'), ('low_stock', 'Low Stock Alert'), ('system_alert', 'System Alert')], max_length=50)),
                ('method', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket')], max_length=20)),
                ('subject_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
            ],
            options={
                'unique_together': {('notification_type', 'method')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('order_updates_email', models.BooleanField(default=True)),
                ('admin_alerts_email', models.BooleanField(default=True)),
                ('flash_sales_email', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_phone_number', models.CharField(blank=True, max_length=20)),
                ('websocket_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('cod_order', 'Cash on Delivery Order'), ('payment_received', 'Payment Received'), ('admin_invitation', 'Admin Invitation'), ('flash_sale_started', 'Flash Sale Started'), ('flash_sale_ending', 'Flash Sale Ending Soon'), ('low_stock', 'Low Stock Alert'), ('system_alert', 'System Alert')], default='system_alert', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('method', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket')], default='in_app', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'), models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx')],
            },
        ),
    ]
